language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
notifications:
  email: false
before_install:
  - git submodule update --init --recursive
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
